### ISSUE TITLE
Using circular buffer read file over USB

### ISSUE THREAD

**Issue by simon88** [SvetlAl/STM32_FS_USB_CDC_device_CMSIS#2]
Hi @SvetlAl 

Just a question I'm trying to use circular buffer to read file on flash card. As soon as I read my file the USB bug (the usb port disappears from the system), and I often have duplicate data displayed.

here is what i've try
In header file
````
#define USB_CDC_CIRC_BUF_USED
#define USB_CDC_CIRC_BUFFER_SIZE (0x200UL*2)
````

I have a function that reads my file like that
````
  char buffer[READ_CHUNK_ENTIRE_FILE];   // READ_CHUNK_ENTIRE_FILE = 64
  int total_bytes_read = 0;

  while (1) {
    int bytes_read = read_file_by_chunks(file_handler, buffer, READ_CHUNK_ENTIRE_FILE);
    if (bytes_read < 0) {
      return;
    } else if (bytes_read == 0) {
      break;
    }

    char temp_buffer[bytes_read];
    snprintf(temp_buffer, sizeof(temp_buffer), "%.*s", bytes_read, buffer);

    display_datas(temp_buffer);

    total_bytes_read += bytes_read;
  }

  return total_bytes_read;
````

Function to display datas
````
void display_datas(const char *datas)
{
  if(use_usb) {
    USB_CDC_send_data((uint8_t *)datas, strlen(datas));
  }else {
    printf("%s\n", datas);
  }
}
````

If I use printf to display datas I don't have bug, and I have exactly what my file contains. It's look like the issue is coming if I try to send more than 64 bytes. Because If i send small string (10-20 chars) I never encouter issue

EDIT: I use FreeRTOS also

**Comment by SvetlAl** [comment]
Maybe the USB memory allocation has something to do with that. The STM bug mentioned in the previous issue. I think so, because I can't say, why the usb port disappears from the system. In the first place this lib waw written for this architecture: no RTOS, all USB data transfers are carried out from the interrupt (max priority), If you utilize USB to send/receive large data chunks (like files or firmware updates) I use a self-made protocol, that ensures, that USB circular buffer is not overrun and data received correctly. Well, you can study this project https://github.com/SvetlAl/STM32_LIN_FDCAN_TOOL . This is an open part of a real commercial project. The USB implementation here can handle an exessive CAN traffic without loss. Just pick the USB code from there. I hope, this can help you.

**Comment by simon88** [comment]
Ok Nice thanks a lot. I'll try to pick usb_cdc directory from STM32_LIN_FDCAN_TOOL
